export const dummyData = [
          { instanceId: "1", videoId: '1', title: "Stream 1", embedUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ", thumbnailUrl: "https://img.youtube.com/vi/dQw4w9WgXcQ/hqdefault.jpg", channelName: "Stream1", isLive: true, viewCount: "250", description: "this asdasd sdajsdnas sadjshna sadjsknajda sadjansd sadjkan" },
          { instanceId: "2", videoId: '2', title: "Stream 2", embedUrl: "https://www.youtube.com/embed/SonfK-rTHPQ", thumbnailUrl: "https://img.youtube.com/vi/SonfK-rTHPQ/hqdefault.jpg", channelName: "Stream2", isLive: false, viewCount: "12422"  },
          { instanceId: "3", videoId: '3', title: "Stream 3", embedUrl: "https://www.youtube.com/embed/ri35YKhV-ME", thumbnailUrl: "https://img.youtube.com/vi/ri35YKhV-ME/hqdefault.jpg", channelName: "Stream3", isLive: true, viewCount: "1337"  },
          { instanceId: "4", videoId: '4', title: "Stream 4", embedUrl: "https://www.youtube.com/embed/WJOAvttDJ-Q", thumbnailUrl: "https://img.youtube.com/vi/WJOAvttDJ-Q/hqdefault.jpg", channelName: "Stream4", isLive: true, viewCount: "67"  },
          { instanceId: "5", videoId: '5', title: "Stream 5", embedUrl: "https://www.youtube.com/embed/yAtUSvVayM0", thumbnailUrl: "https://img.youtube.com/vi/yAtUSvVayM0/hqdefault.jpg", channelName: "Stream5", isLive: false, viewCount: "54230"  },
          { instanceId: "7", videoId: '7', title: "Stream 7", embedUrl: "https://www.youtube.com/embed/ri35YKhV-ME", thumbnailUrl: "https://img.youtube.com/vi/ri35YKhV-ME/hqdefault.jpg", channelName: "Stream3", isLive: true, viewCount: "1337"  },
          { instanceId: "6", videoId: '6', title: "Stream 6", embedUrl: "https://www.youtube.com/embed/WJOAvttDJ-Q", thumbnailUrl: "https://img.youtube.com/vi/WJOAvttDJ-Q/hqdefault.jpg", channelName: "Stream4", isLive: true, viewCount: "67"  },
          { instanceId: "8", videoId: '8', title: "Stream 8", embedUrl: "https://www.youtube.com/embed/yAtUSvVayM0", thumbnailUrl: "https://img.youtube.com/vi/yAtUSvVayM0/hqdefault.jpg", channelName: "Stream5", isLive: false, viewCount: "54230"  },
          
        ]